### ISSUE TITLE
How to configure the Routing, it's not working for me

### ISSUE THREAD

**Issue by xenstar** [tina-hello/doh-cf-workers#1]
I am from CN and wanted to use the NextDNS, but it was always slow. I followed your script and now, it works smoothly. Thank you so much.

**Comment by xenstar** [comment]
Hello, the additional routes, I tried to work on it, but doesn't work.

Do I need to create A record or CNAME in order to work? If so, what should I put in the Target or IPV4 Section? 

![image](https://user-images.githubusercontent.com/55502651/140627211-880bf570-78d3-4dae-88ac-95e69a85efb3.png)

Have you tried that?

**Comment by tina-hello** [comment]
You need a CNAME, the target itself can be any domain, I tried using google.com and my worker still responds correctly. Of course, this assumes the additional routes have been bound to your worker.

**Comment by xenstar** [comment]
I have already created a cname with google.com and it's bound with my route. But doesn't work. :(

**Comment by tina-hello** [comment]
Can you show the error messages you got while testing it with https://github.com/ameshkov/dnslookup?
