### ISSUE TITLE
possible to use multiple upstreams in the worker script?

### ISSUE THREAD

**Issue by miixms** [tina-hello/doh-cf-workers#14]
thanks

**Comment by tina-hello** [comment]
You can randomly pick from a list on each call https://github.com/tina-hello/doh-cf-workers/blob/oisd/index.js

In theory, it's possible to call multiple upstream in parallel and return the first response, but I don't see a situation where it would be useful, seems way more complex for no benefit. More advanced behavior like selecting different upstream based on the requested domain would involve parsing the datagram and the resulting decision tree would be way more complex than this repo intended.

**Comment by tina-hello** [comment]
https://github.com/matthewgall/doh-proxy/blob/main/src/index.ts implement calling multiple upstream in parallel and return the first response
