### ISSUE TITLE
Cf pages

### ISSUE THREAD

**Issue by t-e-s-tweb** [tina-hello/doh-cf-workers#2]
Hello can you please create a tutorial or point me to one on how to add a custom domain to cf pages? I am trying and reading about it but I haven't been successful so far.

**Comment by tina-hello** [comment]
https://developers.cloudflare.com/pages/platform/custom-domains/ should work automatically if your domain is already on Cloudflare, with other providers it depends on their own implementation, basically you need to add CNAME record pointing to your pages.dev URL. Refer to your provider documentation.

**Comment by tina-hello** [comment]
Closed for lack of clarification

**Comment by tina-hello** [comment]
Closing this issue for lack of clarification
