### ISSUE TITLE
Custom path length

### ISSUE THREAD

**Issue by hdid** [tina-hello/doh-cf-workers#26]
Hi
Did you test its length? for example if the path is "/aa-bb" and i put "/aa-bb**b**" on client side; the script replies correctly!?

**Comment by tina-hello** [comment]
Indeed, I don't verify path length. Is that a concern?

**Comment by hdid** [comment]
Well, it is like key and is necessary for private usage.
Thanks

**Comment by tina-hello** [comment]
If you set up, say, `/A2foEkl373dpK` as a path, it would take impractically long time to find even if `/A2foEkl373dpK21LKDJ` is also a valid path, so I don't see this to be a problem.
