### ISSUE TITLE
Consider FSF / OSI approved 0BSD or MIT0 instead of CC0

### ISSUE THREAD

**Issue by ignoramous** [tina-hello/doh-cf-workers#8]
CC0 (public domain dedication as a fallback) isn't legal in all jurisdictions (France and Germany from the top of my head) and some FOSS projects (ex: Fedora) and corps (ex: Google) ban  CC0-licensed `code` (as they see it more of a `content` / `art` license): https://archive.is/ukIC5

Here's an interesting discussion on suitability of CC0 (does not wavier patent rights) and Unlicense (*attempts* public domain dedication) for `code`: https://news.ycombinator.com/item?id=30554087

General recommendation is to use 0BSD / MIT0: https://archive.is/6YgVt

IANAL.

**Comment by tina-hello** [comment]
Thanks, one of my reason choosing CC0 is so the github UI directly shows the rights and obligations, but apparently other licenses would work as well. I'll update it now

**Comment by ignoramous** [comment]
Gotcha.

https://github.com/tina-hello/doh-cf-workers/blob/3487b8c0c8c7ee6b7e941f7f3a5d063d3e27048b/index.js#L1

Needs updating.

```diff
- SPDX-License-Identifier: CC0-1.0
+ SPDX-License-Identifier: 0BSD
```
